version: 2
jobs:
  build:
    working_directory: ~/kernel_perry
    docker:
    - image: gaigecarlos/kbld:200315
      auth:
        username: gaigecarlos
        password: $DOCKER_PASSWORD
    steps:
    - run:
        name: Cloning AK3
        command: git clone https://github.com/RebelLion420/AnyKernel3 -b perry ~/AK3
    - restore_cache:
        keys:
        - src-{{ .Branch }}-{{ .Revision }}
        - src-{{ .Branch }}
        - src-
    - checkout
    - save_cache:
        key: src-{{ .Branch }}-{{ .Revision }}
        paths:
        - "~/kernel_perry/.git"
    - run:
        name: Generating Config
        command: sudo make O=out ARCH=arm CROSS_COMPILE=~/toolchain/bin/arm-linux-gnueabi- perry_defconfig
    - run:
        name: Building Kernel
        command: |
          sudo make O=out ARCH=arm SUBARCH=arm CROSS_COMPILE=~/toolchain/bin/arm-linux-gnueabi- -j$(nproc --all) zImage
          sudo make O=out ARCH=arm SUBARCH=arm CROSS_COMPILE=~/toolchain/bin/arm-linux-gnueabi- -j$(nproc --all) dtbs
          sudo make O=out ARCH=arm SUBARCH=arm CROSS_COMPILE=~/toolchain/bin/arm-linux-gnueabi- -j$(nproc --all) modules
    - run:
        name: Generating Kernel Zip
        command: |
          export OUT=/root/kernel_perry/out
          find $OUT/ -type f -name "*.ko" -exec cp {} /root/AK3/modules/system/lib/modules/ \;
          cp $OUT/arch/arm/boot/zImage ~/AK3
          cp $OUT/arch/arm/boot/dts/qcom/*perry*.dtb ~/AK3
          cd ~/AK3
          zip -r9 RK-perry-$(date +%y%m%d).zip ./* -x .git README.md *placeholder > /dev/null
    - run:
        name: Copying Artifacts
        command: |
          mkdir -p ~/artifacts
          cp ~/AK3/*.zip ~/artifacts
          cp ~/AK3/zImage ~/artifacts
    - store_artifacts:
        path: ~/artifacts
workflows:
  version: 2
  workflow:
    jobs:
      - build:
          filters:
            branches:
              only:
                - cm-14.1
                - test/als
